### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by icemac** [zopefoundation/five.customerize#17]
Would it be possible to cut a new release of this package?

@esteele @tisto According to PyPI you are allowed to do so.
I could do it myself, if you give me (`icemac`) the necessary PyPI permission.

**Comment by icemac** [comment]
@esteele @tisto Ping. A new release of `five.customerize` is still a good thing or getting `PyPI` rights would be even better.

**Comment by icemac** [comment]
Okay, as this repository seems to be Plone-only, let's keep it this way.

**Comment by mauritsvanrees** [comment]
@icemac I could still give you PyPI rights if you want. If you need such rights in a package and you see the `plone` user already has rights: this is the account of the Plone Release Team, so you can ping me. But pinging the others like you did should have worked too.

But I expect this package is indeed only used in Plone.

**Comment by dataflake** [comment]
Would this package be better off in the plone organization?

**Comment by icemac** [comment]
> Would this package be better off in the plone organization?

I'd support this suggestion.

**Comment by icemac** [comment]
I created #18 for the possible movement to the plone organization, so we do not discuss in a closed only loosely connected issue.
